export const SELECT_NUMBER = 'SELECT_NUMBER';
export const UNSELECT_NUMBER = 'UNSELECT_NUMBER';
export const PROCESS_ANSWER = 'PROCESS_ANSWER';
export const REDRAW = 'REDRAW';
export const SET_RANDOM_NUMBER_OF_STARS = 'SET_RANDOM_NUMBER_OF_STARS';
export const REMOVE_SELECTED_NUMBERS = 'REMOVE_SELECTED_NUMBERS';
export const RESET_GAME = 'RESET_GAME';
export const UPDATE_DONE_STATUS = 'UPDATE_DONE_STATUS';
